spring.application.name=notes-spring-security

#------------------------------------------------------
# DB CONFIG DETAILS
#------------------------------------------------------
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.initialization-mode=always

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update

#------------------------------------------------------
# JWT CONFIG DETAILS
#------------------------------------------------------
spring.app.jwtSecret=k3R2f7aV6tY9pQ2uZx1wN8sL4eT0bM7rF5dP8uV2gC9qH1xJ3aK6zW4mB7nD0yP9
spring.app.jwtExpirationMs=900000
spring.app.refreshTokenExpirationMs=604800000